-- Ensure Client_Accounts has a proper primary key and identity column for inserts
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns 
    WHERE table_schema = 'public' 
      AND table_name = 'Client_Accounts' 
      AND column_name = 'id' 
      AND is_identity = 'YES'
  ) THEN
    ALTER TABLE public."Client_Accounts"
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    WHERE t.relname = 'Client_Accounts' AND c.contype = 'p'
  ) THEN
    ALTER TABLE public."Client_Accounts" ADD PRIMARY KEY (id);
  END IF;
END $$;

-- Ensure upserts work on user_id
CREATE UNIQUE INDEX IF NOT EXISTS client_accounts_user_id_key ON public."Client_Accounts" (user_id);

-- Optional but recommended: avoid duplicate emails & usernames
CREATE UNIQUE INDEX IF NOT EXISTS client_accounts_email_key ON public."Client_Accounts" (email);
CREATE UNIQUE INDEX IF NOT EXISTS client_accounts_username_key ON public."Client_Accounts" (username);