-- Link Accounts and Bookings, enforce unique email, and auto-create accounts on signup

-- 1) Ensure Client_Accounts.id is auto-generated (identity)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'Client_Accounts'
      AND column_name = 'id'
      AND is_identity = 'YES'
  ) THEN
    ALTER TABLE public."Client_Accounts"
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- 2) Make email unique (case-insensitive)
CREATE UNIQUE INDEX IF NOT EXISTS client_accounts_email_unique
ON public."Client_Accounts"(lower(email))
WHERE email IS NOT NULL;

-- 3) Speed up lookups by email on bookings
CREATE INDEX IF NOT EXISTS idx_client_bookings_email
ON public."Client_Bookings"(lower(email))
WHERE email IS NOT NULL;

-- 4) Add a foreign key from bookings to accounts (client_id -> accounts.id)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_schema = 'public'
      AND table_name = 'Client_Bookings'
      AND constraint_name = 'client_bookings_client_id_fkey'
  ) THEN
    ALTER TABLE public."Client_Bookings"
    ADD CONSTRAINT client_bookings_client_id_fkey
    FOREIGN KEY (client_id)
    REFERENCES public."Client_Accounts"(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL;
  END IF;
END $$;

-- 5) Create the trigger to auto-insert Client_Accounts rows for new auth users
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'on_auth_user_created'
  ) THEN
    CREATE TRIGGER on_auth_user_created
      AFTER INSERT ON auth.users
      FOR EACH ROW
      EXECUTE PROCEDURE public.handle_new_user_account();
  END IF;
END $$;
