-- Create accounts table to store client profiles with a stable unique id per user
CREATE TABLE IF NOT EXISTS public.accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_uuid UUID NOT NULL,
  email TEXT,
  first_name TEXT,
  last_name TEXT,
  phone TEXT,
  stripe_customer_id TEXT,
  default_payment_method_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT accounts_user_uuid_unique UNIQUE (user_uuid)
);

-- Enable RLS
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;

-- Policies
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'accounts' AND policyname = 'Users can view their own account (accounts)'
  ) THEN
    CREATE POLICY "Users can view their own account (accounts)"
    ON public.accounts FOR SELECT
    USING (auth.uid() = user_uuid);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'accounts' AND policyname = 'Users can update their own account (accounts)'
  ) THEN
    CREATE POLICY "Users can update their own account (accounts)"
    ON public.accounts FOR UPDATE
    USING (auth.uid() = user_uuid);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'accounts' AND policyname = 'Users can insert their own account (accounts)'
  ) THEN
    CREATE POLICY "Users can insert their own account (accounts)"
    ON public.accounts FOR INSERT
    WITH CHECK (auth.uid() = user_uuid);
  END IF;
END $$;

-- Index for case-insensitive email uniqueness and lookup
CREATE UNIQUE INDEX IF NOT EXISTS accounts_email_unique
ON public.accounts (lower(email))
WHERE email IS NOT NULL;

-- updated_at trigger
CREATE TRIGGER update_accounts_updated_at
BEFORE UPDATE ON public.accounts
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Function to auto-create accounts row on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user_accounts()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
BEGIN
  INSERT INTO public.accounts (user_uuid, email, first_name, last_name, phone)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data ->> 'first_name',
    NEW.raw_user_meta_data ->> 'last_name',
    NEW.raw_user_meta_data ->> 'phone'
  )
  ON CONFLICT (user_uuid) DO NOTHING;
  RETURN NEW;
END;
$function$;

-- Trigger to run on auth.users insert (in addition to any existing triggers)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'on_auth_user_created_accounts'
  ) THEN
    CREATE TRIGGER on_auth_user_created_accounts
      AFTER INSERT ON auth.users
      FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user_accounts();
  END IF;
END $$;
