// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azgnzhtqoyqlixfhlkyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6Z256aHRxb3lxbGl4Zmhsa3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDkxNzEsImV4cCI6MjA2OTkyNTE3MX0.l3Wb6k1LoB0Qgtg8tsZI-rtYNqLvNK8OaxyoFToClDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});